from datetime import datetime, date, time 
import telebot
from telebot import types
import psycopg2

token = "2123011997:AAHC7Js79WXP1Tu9_xD20b_g358IaJ5EOpY"

bot = telebot.TeleBot(token)

conn = psycopg2.connect(database="timetable",
                        user="postgres",
                        password="21082003",
                        host="localhost",
                        port="5432")

cursor = conn.cursor()

start = date(2021, 9, 1)
d = datetime.now() 
dof = datetime.isoweekday(d)
week = d.isocalendar()[1] - start.isocalendar()[1] + 1

if week%2 == 1:
  top_week = True
else:
  top_week = False

@bot.message_handler(commands=['start'])
def start(message):
    keyboard = types.ReplyKeyboardMarkup()
    keyboard.row("/mtuci", "/help", "/week", "расписание")
    bot.send_message(message.chat.id, 'Выберите одну из предложенных команд.', reply_markup=keyboard)

@bot.message_handler(commands = ['week'])
def week(message):
    if top_week:
        bot.send_message(message.chat.id, 'Сейчас верхняя неделя.')
    else:
        bot.send_message(message.chat.id, 'Сейчас нижняя неделя.') 

@bot.message_handler(commands=['help'])
def help(message):
    bot.send_message(message.chat.id, 'Это бот был создан для успешной сдачи сессии.')
    bot.send_message(message.chat.id, 'И для просмотра расписания группы БВТ2107 института МТУСИ.')
    bot.send_message(message.chat.id, '/mtuci — эта команда покажет вам ссылку на официальный сайт института мутси.')
    bot.send_message(message.chat.id, '/week — подскажет вам какая сейчас неделя, четная или нечетная.')
    bot.send_message(message.chat.id, 'Для того, что бы увидеть расписание, ведите сообщение "расписание".')
                    
@bot.message_handler(commands=['mtuci'])
def mtuci(message):
    bot.send_message(message.chat.id, 'https://mtuci.ru/')


@bot.message_handler(content_types=['text'])
def answer(message):
    if message.text.lower() == "расписание":
        a = telebot.types.ReplyKeyboardRemove()
        bot.send_message(message.chat.id, 'Выберите нужный вариант.', reply_markup=a)
        b = telebot.types.ReplyKeyboardMarkup()
        b.row("текущая неделя", "следующая неделя")
        bot.send_message(message.chat.id, 'Напишите интересующий вас день недели, либо выберите вариант с кнопок.', reply_markup=b)
    elif message.text.lower() == "понедельник":
        bot.send_message(message.chat.id, 'Понедельник')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 1 ')
        records = list(cursor.fetchall())
        print(records)
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 1 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 2 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 2 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 3 ')
            records = list(cursor.fetchall())
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 16 ')
            records = list(cursor.fetchall())   
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 5 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
    elif message.text.lower() == "вторник":
        bot.send_message(message.chat.id, 'Вторник')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 4 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 13 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 5 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 17 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 6 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 17 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 14 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
    elif message.text.lower() == "среда":
        bot.send_message(message.chat.id, 'Среда')
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 10 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 8 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 12 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            bot.send_message(message.chat.id,'Сегодня пар нет. Прекрасная возможность закрыть долги.')
    elif message.text.lower() == "четверг":
        bot.send_message(message.chat.id, 'Четверг')
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 9 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 4 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 18 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")            
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 9 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 4 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 19 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")  
    elif message.text.lower() == "пятница":
        bot.send_message(message.chat.id, 'Пятница')
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 10 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 8 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 11 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 17 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")    
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 12 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}") 
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 13 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}") 
    elif message.text.lower() == "суббота":
        bot.send_message(message.chat.id, 'Суббота')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 14 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 9 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 15 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 11 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
    elif message.text.lower() == "текущая неделя": 
        bot.send_message(message.chat.id, 'Расписание на всю неделю:')        
        bot.send_message(message.chat.id, 'Понедельник')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 1 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 1 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 2 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 2 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 3 ')
            records = list(cursor.fetchall())
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 16 ')
            records = list(cursor.fetchall())   
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 5 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Вторник')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 4 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 13 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 5 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 17 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 6 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 17 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 14 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Среда')
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 10 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 8 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 12 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            bot.send_message(message.chat.id,'Сегодня пар нет. Прекрасная возможность закрыть долги.')
        bot.send_message(message.chat.id, 'Четверг')
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 9 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 4 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 18 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")            
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 9 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 4 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 19 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Пятница')
        if top_week:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 10 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 8 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 11 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 17 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")    
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 12 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}") 
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 13 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Суббота')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 14 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 9 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 15 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 11 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}") 
    elif message.text.lower() == "следующая неделя": 
        bot.send_message(message.chat.id, 'Расписание на всю неделю:')        
        bot.send_message(message.chat.id, 'Понедельник')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 1 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 1 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 2 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 2 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        if top_week == False:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 3 ')
            records = list(cursor.fetchall())
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 16 ')
            records = list(cursor.fetchall())   
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 5 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Вторник')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 4 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 13 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 5 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 17 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        if top_week == False:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 6 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 17 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 14 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Среда')
        if top_week == False:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 10 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 8 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 12 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            bot.send_message(message.chat.id,'Сегодня пар нет. Прекрасная возможность закрыть долги.')
        bot.send_message(message.chat.id, 'Четверг')
        if top_week == False:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 9 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 4 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        else:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 18 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")            
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 9 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 4 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 19 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 7 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Пятница')
        if top_week == False:
            cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 10 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
            cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 8 ')
            records = list(cursor.fetchall())
            bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 11 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 17 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")    
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 12 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}") 
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 13 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 16 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        bot.send_message(message.chat.id, 'Суббота')
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 14 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 9 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}")
        cursor.execute(f'SELECT subject, room_numb, start_time FROM schedule.fact WHERE id = 15 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}, {records[0][1]}, {records[0][2]}") 
        cursor.execute(f'SELECT full_name FROM schedule.teacher WHERE id = 11 ')
        records = list(cursor.fetchall())
        bot.send_message(message.chat.id, f"{records[0][0]}") 
    else:
        bot.send_message(message.chat.id, 'Я вас не понял. Попробуйте использовать команду /help.')

bot.polling()